### ISSUE TITLE
epub and pdf versions not available

### ISSUE THREAD

**Issue by pssguy** [cpsievert/plotly_book#1]
404

**Comment by znmeb** [comment]
I cloned the repo and tried to build them on my workstation but I gave up - too many packages need to be installed to even knit index.Rmd.

**Comment by znmeb** [comment]
Bumping this up in my queue - I need to learn plotly and integrate it into my DFS analytics workflow. I'm going to fork the book and see if I can get PDF builds and some scripts. I'll probably do it in an Ubuntu Docker image from the command line; I want a minimized dependency set.

**Comment by znmeb** [comment]
Fork is done - https://github.com/znmeb/plotly_book/blob/master/ubuntu_build_scripts/README.md. The PDF build doesn't work, though - there's a missing screenshot.

I'm going to move this issue to the main Plotly repo - it seems to be very active and they have a full-fledged contributors' guide.

**Comment by cpsievert** [comment]
I removed these buttons -- if there is ever going to be a pdf version, it will be an actual book, available in print
