### ISSUE TITLE
Section 1.2.2 Modifying layers refers to a plot with 3 traces, but shows only 1 trace

### ISSUE THREAD

**Issue by mlduarte** [cpsievert/plotly_book#11]
On arriving at section _1.2.2 Modifying Layers_, p was previously assigned as follows:

`p <- ggplot(fortify(gold), aes(x, y)) + geom_line()`

This section says that there are three traces within the data, however there is only a "0" appearing under data.  In contrast, if p is assigned as follows,  I see a 0, 1 and 2 which I understand to be the three traces referred to in the section

`p <- ggplot(mtcars, aes(x = wt, y = mpg)) +
   geom_point() + geom_smooth()

plotly_json(p)
`
This is my first look at plotly, so I could be wrong! but otherwise it is not clear ....

**Comment by cpsievert** [comment]
Thanks!
