### ISSUE TITLE
Tags for linked_highlighting don't link to anywhere

### ISSUE THREAD

**Issue by mlduarte** [cpsievert/plotly_book#12]
linked_highlighting is tagged in the following sections (but clicking on 'linked_highlighting' does not link to more information on the topic)

> 2.1.3.2 Parallel Coordinates
> Section 2.3 Bars & Histograms, note 7: This has some interesting applications for **linked highlighting** as it allows for summary statistics to be computed on-the-fly based on a selection

**Comment by cpsievert** [comment]
Thanks!
