### ISSUE TITLE
In ggplotly the legend for size variable is not showing properly 

### ISSUE THREAD

**Issue by EnricowithR** [cpsievert/plotly_book#15]
As in the first chart at this page:
https://plotly-book.cpsievert.me/key-frame-animations.html
the one resulting from this code:
data(gapminder, package = "gapminder")
gg <- ggplot(gapminder, aes(gdpPercap, lifeExp, color = continent)) +
  geom_point(aes(size = pop, frame = year, ids = country)) +
  scale_x_log10()
ggplotly(gg)

The legend for size variable is not visible properly, the text is half cut.
Is there anything to do to see it in full?

**Comment by cpsievert** [comment]
https://github.com/ropensci/plotly/issues/new is better place for issues like this.

That being said, there currently isn't anything I can do about this problem due to limitations of plotly.js
