### ISSUE TITLE
2.6 Other 3D plots

### ISSUE THREAD

**Issue by eijoac** [cpsievert/plotly_book#23]
"the x and y attributes do not have to be provided, but if they are, the length of x should match the number of rows in the matrix and y should match the number of columns."

The statement is not correct. It's exactly the opposite: the length of x should match the number of columns in the matrix and y should match the number of rows. (i agree that plotly is bit weird in this regard.)

```
x <- seq_len(ncol(volcano)) + 100
y <- seq_len(nrow(volcano)) + 500
plot_ly() %>% add_surface(x = ~x, y = ~y, z = ~volcano)
```

**Comment by cpsievert** [comment]
Good catch, thanks!
