### ISSUE TITLE
use of “ instead of " means no copy/paste in Windows

### ISSUE THREAD

**Issue by timelyportfolio** [cpsievert/plotly_book#4]
This is very minor, but when I copy/paste in Windows some of the code examples give an error since `“` is used instead of `"`.

**Comment by cpsievert** [comment]
Huh, is this relevant for all the examples? Or just a portion of them?

**Comment by cpsievert** [comment]
Closing since I don't see any use of `“` in the examples anymore, please reopen if I'm wrong.
