### ISSUE TITLE
Any chance to backport some of the packages used ?

### ISSUE THREAD

**Issue by hgfernan** [cpsievert/plotly_book#71]
1st of all, congratulations to @cpsievert for a great and enlightening book.

I'm using the standard variety of R, from the current package of the stable Debian repo. It's still R 3.3.3, while some of the packages in the book, like `trelliscopejs` demand R 3.4.0, at least. 

So, my question is: what about backporting `trelliscope` to R 3.3.3 ?

Or maybe using only packages compatible while R 3.3.3 ?

While downloading and compiling R 3.4.0 is probably not that difficult, maybe some of your readers are also using versions older than 3.4.0.

Thank you !

**Comment by cpsievert** [comment]
I won't be backporting, but I can maybe include a requirement about R version

**Comment by hgfernan** [comment]
Great, that would be nice, @cpsievert  !

Many of the readers of your great book will probably use R from their Linux distribution, and that's usually a little older.
